### ¿Qué es una pseudo inversa de Moore Penrose y cómo calcularla?


La pseudo inversa de Moore Penrose es una aplicación directa de SVD, que nos permite resolver en determinados momentos sistemas de ecuaciones lineales con múltiples soluciones.

Un sistema de ecuaciones lineales puede ser A*x = B. En el caso de que exista la solución podemos denotarlo como 
x = Aˆ-1 * B.

**Pero qué pasa cuando no existe Aˆ-1?**

Tenemos que buscar otro matriz a la cual llamaremos A pseudo inversa ó A_pse, con la característica de que cuando hablamos de A * A_pse = la identidad (o muy cercana a ella).

In [2]:
import numpy as np

# No nos mostrará los números muy cercanos al zero
np.set_printoptions(suppress=True)

A pseudo inversa será igual a `V` (matriz obtuvida por la descomposición SVD) por la Diagonal (asociada a la pseudo inversa) multiplicado por `U` traspuesta.

In [30]:
# Generamos nuestra matriz para trabajarla
A = np.array([[2,3], [5, 7], [11,13]])
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [33]:
# Descomponemos la matriz con Single Values Decomposition

U, D, V = np.linalg.svd(A)

# Revisamos cada una de las matrices resultadas de la descomposición

print("U")
print(U)

print("D")
print(D)

print("V")
print(V)

U
[[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]
D
[19.40321383  0.71783924]
V
[[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]


In [9]:
# Para calcular el valor de D pseudo, necesitamos hacer varios pasos.

# Primero definimos una matriz de ceros, que tenga de tamanio el mismo de nuestra matriz original A.
# para después de esto, trasponerla.

D_pse = np.zeros((A.shape[0], A.shape[1])).T

print(D_pse)

[[0. 0. 0.]
 [0. 0. 0.]]


Como nuestra matriz D es una matriz sólo con valores en la diagonal (matriz cuadrada con valores en la diagonal)
Cuando necesitamos calcular el recíproco de esta matriz es como calcular la inversa
porque es igual que calcular 1 sobre cada elemento que tenemos en la diagonal
entonces nos conviene directamente calcular la inversa de los valores de la matriz D


In [10]:
# Primero vemos los valores de D_pse

print("Valores a reemplazar en D_pse")
print(D_pse[:D.shape[0], :D.shape[0]])

Valores a reemplazar en D_pse
[[0. 0.]
 [0. 0.]]


In [13]:
print("Valores que pondremos en D_pse")
print(np.linalg.inv(np.diag(D))) # Inversa de nuestra matriz D

Valores que pondremos en D_pse
[[0.05153785 0.        ]
 [0.         1.39306957]]


In [15]:
# Calculamos la inversa de los valores singulares que tenemos en D_pse.
# Reemplazamos los valores que calzan con nuestra diagonal.

print("D_pse con valores diagonales calculados")
D_pse[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D))
print(D_pse)

D_pse
[[0.05153785 0.         0.        ]
 [0.         1.39306957 0.        ]]


In [17]:
# Una vez tenemos calculada la matriz D_pse, ahora reconstruimos quien es nuestra pseudoinversa

A_pse = V.T.dot(D_pse).dot(U.T)
print(A_pse)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [34]:
# Calculando la pseudo inversa de A a través del método de numpy. 

A_pse_calc = np.linalg.pinv(A)
print(A_pse_calc)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [20]:
# Queremos ver que, cuando aplicamos la A pseudo matriz a nuestra matriz, nos muestre un resultado
# muy cercano a la identidad
print(A_pse.dot(A))

[[ 1. -0.]
 [ 0.  1.]]


In [21]:
# Desactivamos el mute de números cercanos al cero
np.set_printoptions(suppress=False)

In [22]:
# Vemos el número completo, aún así es muy cercano a la identidad
print(A_pse.dot(A))

[[ 1.00000000e+00 -8.88178420e-16]
 [ 2.66453526e-15  1.00000000e+00]]


Otra manera de calcular una pseudo inversa ->  

In [29]:
# Otra manera de calcular una pseudo inversa. 

A_pse_2 = np.linalg.inv(A.T.dot(A)).dot(A.T)
print(A_pse_2)
print()
print(A_pse_calc)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]
